/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modultiga;

/**
 *
 * @author LENOVO
 */
public class Satu extends javax.swing.JFrame {

    /**
     * Creates new form Satu
     */
    public Satu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pTengah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbPenulis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPenerbit = new javax.swing.JTextField();
        tfTglTerbit = new javax.swing.JTextField();
        tfPenulis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDeskripsi = new javax.swing.JTextArea();
        lbJudul = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        pBawah = new javax.swing.JPanel();
        lbBuku1 = new javax.swing.JLabel();
        lbBuku2 = new javax.swing.JLabel();
        lbBuku3 = new javax.swing.JLabel();
        btBuku1 = new javax.swing.JButton();
        btBuku2 = new javax.swing.JButton();
        btBuku3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btKeluar = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAtas.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERPUSTAKAAN CENDIAKA");

        jLabel2.setText("Jl. Ahmad Yani No. 135 Lakarsanti Surabaya");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modultiga/icon1.png"))); // NOI18N

        javax.swing.GroupLayout pAtasLayout = new javax.swing.GroupLayout(pAtas);
        pAtas.setLayout(pAtasLayout);
        pAtasLayout.setHorizontalGroup(
            pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pAtasLayout.setVerticalGroup(
            pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtasLayout.createSequentialGroup()
                .addGroup(pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAtasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAtasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pAtas, java.awt.BorderLayout.PAGE_START);

        pTengah.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Penerbit               :");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Tanggal Terbit     :");

        lbPenulis.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        lbPenulis.setText("Penulis                :");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel6.setText("Deskripsi             :");

        tfPenerbit.setBackground(new java.awt.Color(255, 204, 102));
        tfPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPenerbitActionPerformed(evt);
            }
        });

        tfTglTerbit.setBackground(new java.awt.Color(255, 204, 102));
        tfTglTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTglTerbitActionPerformed(evt);
            }
        });

        tfPenulis.setBackground(new java.awt.Color(255, 204, 102));

        tfDeskripsi.setBackground(new java.awt.Color(255, 204, 102));
        tfDeskripsi.setColumns(20);
        tfDeskripsi.setRows(5);
        jScrollPane1.setViewportView(tfDeskripsi);

        lbJudul.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        lbJudul.setText("Judul                   :");

        tfJudul.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout pTengahLayout = new javax.swing.GroupLayout(pTengah);
        pTengah.setLayout(pTengahLayout);
        pTengahLayout.setHorizontalGroup(
            pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTengahLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pTengahLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTengahLayout.createSequentialGroup()
                        .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pTengahLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbPenulis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pTengahLayout.createSequentialGroup()
                                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(lbJudul, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPenerbit)
                            .addComponent(tfTglTerbit)
                            .addComponent(tfPenulis)
                            .addComponent(tfJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pTengahLayout.setVerticalGroup(
            pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTengahLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJudul)
                    .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTglTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPenulis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31))
        );

        getContentPane().add(pTengah, java.awt.BorderLayout.CENTER);

        pBawah.setBackground(new java.awt.Color(255, 255, 153));

        lbBuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modultiga/bumi1.jpg"))); // NOI18N

        lbBuku2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modultiga/Kata1.jpg"))); // NOI18N

        lbBuku3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modultiga/SangPemimpi1.jpg"))); // NOI18N

        btBuku1.setText("Deskripsi");
        btBuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuku1ActionPerformed(evt);
            }
        });

        btBuku2.setText("Deskripsi");
        btBuku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuku2ActionPerformed(evt);
            }
        });

        btBuku3.setText("Deskripsi");
        btBuku3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuku3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setText("BUMI");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setText("KATA");

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel13.setText("SANG PEMIMPI");

        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBawahLayout = new javax.swing.GroupLayout(pBawah);
        pBawah.setLayout(pBawahLayout);
        pBawahLayout.setHorizontalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBawahLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBuku1)
                    .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pBawahLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel11))
                        .addComponent(lbBuku1)))
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBawahLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuku2))
                    .addGroup(pBawahLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBawahLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12))
                            .addComponent(lbBuku2))))
                .addGap(12, 12, 12)
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBawahLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(42, 42, 42))
                    .addGroup(pBawahLayout.createSequentialGroup()
                        .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBawahLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lbBuku3))
                            .addGroup(pBawahLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btBuku3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBawahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btReset)
                .addGap(51, 51, 51)
                .addComponent(btKeluar)
                .addGap(130, 130, 130))
        );
        pBawahLayout.setVerticalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuku2)
                    .addComponent(lbBuku1)
                    .addComponent(lbBuku3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBawahLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11))
                    .addGroup(pBawahLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGap(3, 3, 3)
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuku3)
                    .addComponent(btBuku2)
                    .addComponent(btBuku1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKeluar)
                    .addComponent(btReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuku1ActionPerformed
        tfJudul.setText("Bumi");
        tfPenerbit.setText("Gramedia Pustaka Utama");
        tfTglTerbit.setText("16 Januari 2014");
        tfPenulis.setText("Tere Liye");      
        tfDeskripsi.setText("Novel Bumi mengisahkan seorang remaja \nperempuan bernama Raib. Dikisahkan \nbahwa Raib bisa bertemu sosok kurus \ntinggi bernama Tamus. Makhluk kurus dan \ntinggi itu muncul di dalam cermin \nkamar Raib.");        
    }//GEN-LAST:event_btBuku1ActionPerformed

    private void tfTglTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTglTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTglTerbitActionPerformed

    private void tfPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPenerbitActionPerformed

    private void btBuku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuku2ActionPerformed
        tfJudul.setText("Kata");
        tfPenerbit.setText("Gagas Media");
        tfTglTerbit.setText("07 November 2018");
        tfPenulis.setText("Rintik Sedu");      
        tfDeskripsi.setText("Novel Kata oleh Rintik Sedu bercerita \ntentang hati Binta yang penuh bimbang. \nBinta terjebak dalam masa lalu yang \nbelum usai, sementara cinta baru yang \nhangat sudah siap menyambut dirinya \nuntuk melangkah maju. ");
    }//GEN-LAST:event_btBuku2ActionPerformed

    private void btBuku3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuku3ActionPerformed
        tfJudul.setText("Sang Pemimpi");
        tfPenerbit.setText("Benteng Pustaka");
        tfTglTerbit.setText("Juli 2006");
        tfPenulis.setText("Andrea Hirata");
        tfDeskripsi.setText("Dalam novel ini, Andrea mengeksplorasi \nhubungan persahabatannya dengan dua anak \nyatim piatu, Arai Ichsanul Mahidin \ndan Jimbron, serta kekuatan mimpi yang \ndapat membawa Andrea dan Arai melanjutkan \nstudi ke Sorbonne, Paris, Prancis.");
    }//GEN-LAST:event_btBuku3ActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        tfJudul.setText("");
        tfPenerbit.setText("");
        tfTglTerbit.setText("");
        tfPenulis.setText("");
        tfDeskripsi.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Satu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuku1;
    private javax.swing.JButton btBuku2;
    private javax.swing.JButton btBuku3;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuku1;
    private javax.swing.JLabel lbBuku2;
    private javax.swing.JLabel lbBuku3;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbPenulis;
    private javax.swing.JPanel pAtas;
    private javax.swing.JPanel pBawah;
    private javax.swing.JPanel pTengah;
    private javax.swing.JTextArea tfDeskripsi;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPenulis;
    private javax.swing.JTextField tfTglTerbit;
    // End of variables declaration//GEN-END:variables
}
